name: Post welcome comment
on:
 push:
  branches: [ main ]
 pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: build stage one
    runs-on: ubuntu-latest

    steps:
      - name: step one  
        uses: actions/checkout@v4

      - name: steps two 
        run: echo "step two"
    
