name: Post welcome comment
on:
 push:
  branches: [ main ]
 pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: build one
    runs-on: ubuntu-latest

    steps:
      - name: print event trigger
        run: echo ${{ github.event_name }}
      - name: step one  
        uses: actions/checkout@v4

      - name: steps two 
        run: echo "step two"
    
